#!/usr/bin/env bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global --file=~/.brewfile
  fi

  bash ~/.config/yadm/bootstrap_mac

fi



################################
##### Setup TMUX  ##############
################################

echo "RUN TMUX Configuration"

# Link tmux conf
ln -sfn ~/.config/tmux/tmux.conf ~/.tmux.conf;

# Install TMUX Plugin Manger if missing
if [ ! -e "$HOME/.config/tmux/plugins/tpm" ]; then
    printf "WARNING: Cannot find TPM (Tmux Plugin Manager) at default location: \$HOME/.tmux/plugins/tpm.\n Downloading now"
    mkdir -p ~/.config/tmux/plugins/
    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
fi


# Install Tmux Plugins
echo "Install TPM plugins"
tmux new -d -s __noop >/dev/null 2>&1 || true 
tmux set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins"
"$HOME"/.config/tmux/plugins/tpm/bin/install_plugins || true
tmux kill-session -t __noop >/dev/null 2>&1 || true
printf "OK: Completed\n"


##################################
#### Setup Starship ##############
##################################
if ! command -v starship >/dev/null 2>&1; then
    echo "Installing Starship"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi


